<h3>Советуем добавить миниатюры</h3>
<? global $arFilter;
$arFilter = [
	'SECTION_CODE' => "miniatyury" // miniatures
];
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section",
	"catalog_block",
	Array(
		"FILTER_NAME" => "arFilter",
		"={\"ADDITIONAL_PICT_PROP_\".\$ElementOfferIblockID}" => $arParams["OFFER_ADD_PICT_PROP"],
		"={\"CART_PROPERTIES_\".\$arParams[\"IBLOCK_ID\"]}" => $arParams["PRODUCT_PROPERTIES"],
		"={\"OFFER_TREE_PROPS_\".\$ElementOfferIblockID}" => $arParams["OFFER_TREE_PROPS"],
		"={\"PROPERTY_CODE_\".\$arParams[\"IBLOCK_ID\"]}" => $arParams["LIST_PROPERTY_CODE"],
		"ACTION_VARIABLE" => "ACTION",
		"ADDITIONAL_PICT_PROP_20" => "MORE_PHOTO",
		"ADDITIONAL_PICT_PROP_23" => "MORE_PHOTO",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"BASKET_URL" => SITE_DIR."basket/",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "86400",
		"CACHE_TYPE" => "N",
		"CART_PROPERTIES_20" => array(),
		"CART_PROPERTIES_23" => array(0=>"undefined",),
		"COMPONENT_TEMPLATE" => "catalog_block_slider",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => $arParams["CURRENCY_ID"],
		"DEPTH" => "2",
		"DISPLAY_COMPARE" => "Y",
		"HIDE_NOT_AVAILABLE" => "Y",
		"IBLOCK_ID" => "2",
		"IBLOCK_TYPE" => "aspro_next_catalog",
		"ID" => "",
		"LABEL_PROP_20" => "-",
		"LINE_ELEMENT_COUNT" => "4",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => $arParams["MESS_NOT_AVAILABLE"],
		"OFFER_TREE_PROPS_23" => array(),
		"PAGE_ELEMENT_COUNT" => "4",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => $arParams["PRICE_CODE"],
		"PRICE_VAT_INCLUDE" => "N",
		"PRODUCT_ID_VARIABLE" => "ID",
		"PRODUCT_PROPS_VARIABLE" => $arParams["PRODUCT_PROPS_VARIABLE"],
		"PRODUCT_QUANTITY_VARIABLE" => $arParams["PRODUCT_QUANTITY_VARIABLE"],
		"PRODUCT_SUBSCRIPTION" => "N",
		"PROPERTY_CODE_20" => array(0=>"",1=>"",),
		"PROPERTY_CODE_23" => array(0=>"",1=>"",),
		"RCM_TYPE" => (isset($arParams['BIG_DATA_RCM_TYPE'])?$arParams['BIG_DATA_RCM_TYPE']:''),
		"SALE_STIKER" => $arParams["SALE_STIKER"],
		"SECTION_ID" => "", //miniatures
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_FROM_SECTION" => "N",
		"SHOW_IMAGE" => "Y",
		"SHOW_NAME" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_PRODUCTS_20" => "Y",
		"SHOW_RATING" => "N",
		"STIKERS_PROP" => $arParams["STIKERS_PROP"],
		"STORES" => ["1"],
		"TEMPLATE_THEME" => "blue",
		"USE_PRODUCT_QUANTITY" => "N",
		"USE_REGION" => "N",
		"CUSTOM_HIDE_BOTTOM_NAV" => "Y", //hide navigation hack
		"ELEMENT_SORT_FIELD" => "rand",
        "ELEMENT_SORT_FIELD2" => "id",
        "ELEMENT_SORT_ORDER" => "asc",
        "ELEMENT_SORT_ORDER2" => "desc",
		"SET_TITLE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SEF_MODE" => "Y",
		"DETAIL_URL" => "",
		'COMPATIBLE_MODE' => 'Y',
	),
false,
Array(
	'HIDE_ICONS' => 'Y'
)
);?>